libbanshee: Remove unused wanted_size variable (bgo#663281)
This fixes the following warning:
banshee-player-vis.c: In function '_bp_vis_pipeline_setup':
banshee-player-vis.c:206:10: error: variable 'wanted_size' set but not used
[-Werror=unused-but-set-variable]

Signed-off-by: Bertrand Lorentz <bertrand.lorentz@gmail.com>